# Generated by Django 4.2.3 on 2023-07-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
