# Generated by Django 4.2.3 on 2023-07-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_classes_studedent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_joined',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='work',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_class',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
